import { ReactNode } from 'react';

import StyledComponentsRegistry from '../lib/StyledComponentsRegistry';

import GlobalStyleThemeProvider from './GlobalStyleThemeProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyleThemeProvider>
            {children}
          </GlobalStyleThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
